<a href="https://colab.research.google.com/github/mahaairshad-shu/MechanicsPython2025/blob/main/Wk1_Sess2_Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![SHU](https://drive.google.com/uc?export=view&id=1oauWClN3B2tjg1AeVHtfjAXZg13d9HXL)

#**Modelling Mechanics of Sports Engineering**
##Week 1
###Session 2 - Introduction to Python


<a target="_blank" href="https://github.com/mahaairshad-shu/MechanicsPython2025">
  <img alt="Link to GitHub" src="https://img.shields.io/badge/link_to-GitHub_repo-blue?logo=github&labelColor=black">

</a><a target="_blank" href="https://shuspace.shu.ac.uk/ultra/courses/_355862_1/outline">
  <img alt="Access course folder" src="https://img.shields.io/badge/access_course_files-Folder-yellow">
</a>

#Python Language
<div class="markdown-google-sans">
  <h2>About</h2>
</div>

* high-level and easy language.
* is interpreted -> executed line by line, which allows programming to be interactive in a way that is not directly possible with compiled languages like Fortran, C, or Java.
* is free.
* large library of publicly available code.


#Introduction
This notebook gives an introduction to Python programming. We'll learn:

* Variables and data types
* Lists, indexing, append
* Dictionaries
* Numpy (arrays (ones, zeros, full, random), indexing, functions, concatenate)



✅ **Note: Make sure the AI assistant is turned off**

*Tools> Settings> AI assistance> Hide generative AI features*

##1. Variables and data types

We briefly looked at the data types in python in the previous notebook. Below are some more examples.

In [ ]:
# Variables and Data Types

# Variables are used to store data.  In Python, you don't need to explicitly declare a variable's data type.  Python infers the type based on the value assigned.

# Integer
age = 30
print(type(age))

# Float
height = 1.75
print(type(height))

# String
name = "Alice"
print(type(name))

# Boolean
is_student = True
print(type(is_student))

#Run this cell to check if the data types are as expected. [Ctrl+Enter]

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


You can also convert the data type of a variable

In [ ]:
# Type Conversion (Casting).
# Some examples:

# Convert an integer to a string
age_str = str(age)
print(age_str)
print(type(age_str))

30
<class 'str'>


In [ ]:
# Convert a float to an integer
height_int = int(height)
print(height_int)
print(type(height_int))

1
<class 'int'>


In [ ]:
# Convert a string to a float
age_str = "30"
age_float = float(age_str)
print(age_float)
print(type(age_float))

30.0
<class 'float'>


❗Try changing the following string into an integer ❗

In [ ]:
year = "2024"
#year_int =              # uncomment and type code here
#print(type(year_int))

Strings can be concatenated using +

In [ ]:
# String Concatenation
userData = name + " Smith, aged " + str(age)  # Combine strings
userData # Notice that Colab allows to print the contents of a variable by typing its name at the end of the cell

'Alice Smith, aged 30'

##2. Lists
*Lists* are ordered collections of items. It is used to store multiple items in a a single variable.

In [ ]:
# Lists

# A list can contain elements of same or different data types.
my_list = [1, 2, 3, "apple", True]
my_list

[1, 2, 3, 'apple', True]

In [ ]:
# Print length of list
print(len(my_list))

5


In [ ]:
# Accessing elements (indexing)
print(my_list[0])  # Python uses zero-based indexing. First element is indexed at 0
print(my_list[-1]) # Negative indexing starts from the end
print(my_list[2:4]) # Slicing. Start:End-1
print(my_list[2:])

1
True
[3, 'apple']
[3, 'apple', True]


In [ ]:
# Modifying lists
my_list.append(4) # Adds an element to the end
print(my_list)

[1, 2, 3, 'apple', True, 4]


In [ ]:
my_list[2] = "banana"  # Replace an element
print(my_list)

[1, 2, 'banana', 'apple', True, 4]


❗1. Replace the number 1 with 3 and add 'orange' to *my_list* ❗

❗2. Create a *sub_list*   to contain ['banana', 'apple', True] by slicing out the items *my_list* ❗

In [ ]:
# type code here

## 3. Dictionaries

Another useful data type is *dictionaries*. Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys.

In [ ]:
# Dictionaries

# Dictionaries store data in key-value pairs. Keys must be unique and immutable (e.g., strings, numbers).
# items always added as key:value pairs
my_dict = {"name": "Bob", "age": 25, "city": "New York"}
my_dict

{'name': 'Bob', 'age': 25, 'city': 'New York'}

In [ ]:
# alternate way to create and add to dictionary
# useful when the items have to be added later in the code
new_dict = {}               # create an empty dictionary
new_dict["name"] = "Bob"    # add
new_dict["age"] = 25
new_dict["city"] = "New York"
new_dict

{'name': 'Bob', 'age': 25, 'city': 'New York'}

In [ ]:
# Accessing values using keys
print(my_dict["name"])
print(my_dict.get("age"))

Bob
25


In [ ]:
# Adding or modifying key-value pairs
my_dict["occupation"] = "Engineer" # Adds a new key-value pair
print(my_dict)

{'name': 'Bob', 'age': 25, 'city': 'New York', 'occupation': 'Engineer'}


In [ ]:
# Iterating through a Dictionary
for key, value in my_dict.items():
    print(f"Key: {key}, Value: {value}")

Key: name, Value: Bob
Key: age, Value: 25
Key: city, Value: New York
Key: occupation, Value: Engineer


In [ ]:
#Checking for keys:
if "city" in my_dict:
    print("The key 'city' exists in my_dict")

The key 'city' exists in my_dict


In [ ]:
#Removing a key-value pair
del my_dict["city"]
print("Dictionary after deleting the 'city' key-value pair:", my_dict)

Dictionary after deleting the 'city' key-value pair: {'name': 'Bob', 'age': 25, 'occupation': 'Engineer'}


In the dictionary *my_dict*,

❗1. change Bob's age to 27❗

❗2. add Bob's gender ❗

In [ ]:
# type code here

## 4. NumPy

So far we have used the built-in functionalities and data types in Python.
In this section, we explore a very popular library, NumPy (Numerical Python), widely used for working with arrays.

* has functions for working in domain of linear algebra, fourier transform, statistics and matrices.
* array object much more suitable for numerical data, instead of lists.
* can handle large data sets efficiently, with much lower momory footprint.
* allows vectorization! > operations are applied to all elements in an array without the need for explicit loops compared to lists > hence faster.

In [ ]:
import numpy as np  # the library comes pre-installed in Colab environment,
                    # but needs to imported at the top of your code

In [ ]:
# A simple 1D NumPy array
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

notice how *my_array* is different from *my_list*

In [ ]:
my_list

[1, 2, 'banana', 'apple', True, 4]

####Initializing an array

In [ ]:
# Creating NumPy arrays
arr_ones = np.ones((2, 3))  # Create a 2x3 array filled with ones
arr_zeros = np.zeros((3, 2)) # Create a 3x2 array filled with zeros
arr_full = np.full((2, 2), 7) # Create a 2x2 array filled with the value 7
arr_random = np.random.rand(2, 2)  # Create a 2x2 array of random numbers between 0 and 1

print("Ones array:\n", arr_ones)
print("\nZeros array:\n", arr_zeros)
print("\nFull array:\n", arr_full)
print("\nRandom array:\n", arr_random)

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Zeros array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

Full array:
 [[7 7]
 [7 7]]

Random array:
 [[0.10320917 0.94837275]
 [0.1017807  0.59800486]]


In [ ]:
# Print shape of an array
print("Shape of arr_random:", arr_random.shape)

Shape of arr_random: (2, 2)


In [ ]:
# Create an empty numpy array
empty_array = np.array([])

# Add items to the array
empty_array = np.append(empty_array, [1, 2, 3])
empty_array = np.append(empty_array, 4)  # You can append single elements too

empty_array

array([1., 2., 3., 4.])

In [ ]:
# np.linspace creates an array with evenly spaced numbers over a specified interval
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# start: The starting value of the sequence.
# stop: The end value of the sequence.
# num: Number of samples to generate. Default is 50.
# endpoint: If True, stop is the last sample. Otherwise, it is not included. Default is True.

linspace_array = np.linspace(0, 10, 5)  # Create an array of 5 numbers from 0 to 10 (inclusive)
print("linspace_array:", linspace_array)

linspace_array_exclusive = np.linspace(0, 10, 5, endpoint=False) # Create an array of 5 numbers from 0 to 10 (exclusive)
print("linspace_array_exclusive:", linspace_array_exclusive)

linspace_array: [ 0.   2.5  5.   7.5 10. ]
linspace_array_exclusive: [0. 2. 4. 6. 8.]


In [ ]:
# np.arange creates an array with evenly spaced values within a given interval
# np.arange([start,] stop[, step,], dtype=None)
# start: The starting value of the sequence.
# stop: The end value of the sequence (exclusive).
# step: Spacing between values. Default is 1.

arange_array = np.arange(0, 10, 2)  # Create an array with numbers from 0 to 10 (exclusive), with a step of 2
print("arange_array:", arange_array)

arange_array_default_step = np.arange(0,5) # creates an array from 0 to 4
print("arange_array_default_step:", arange_array_default_step)

arange_array: [0 2 4 6 8]
arange_array_default_step: [0 1 2 3 4]


####Indexing

In [ ]:
# Array indexing
print("\nElement at index (0, 1):", arr_random[0, 1])
print("\nFirst row:", arr_random[0, :])
print("\nSecond column:", arr_random[:, 1])


Element at index (0, 1): 0.9483727515494283

First row: [0.10320917 0.94837275]

Second column: [0.94837275 0.59800486]


####Array operations

In [ ]:
# Concatenate arrays along different axes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along the first axis (rows)
concatenated_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows:\n", concatenated_rows)

# Concatenate along the second axis (columns)
concatenated_cols = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along columns:\n", concatenated_cols)

# Using hstack and vstack for horizontal and vertical stacking
horizontal_stack = np.hstack((arr1, arr2))
print("\nHorizontal stack:\n", horizontal_stack)

vertical_stack = np.vstack((arr1, arr2))
print("\nVertical stack:\n", vertical_stack)

Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]

Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Reshape arrays
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array:\n", reshaped_arr)

Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# Concatenating arrays with different shapes
arr3 = np.array([9, 10])
np.shape(arr3)
#Cannot concatenate arrays with mismatched shapes along axis=0
#print("\nConcatenated rows with different shapes:\n", np.concatenate((arr1, arr3), axis=0)) # This will raise an error.

(2,)

In [ ]:
# Need to reshape arr3 for concatenation along axis=0
arr3_reshaped = arr3.reshape(1,2)
print("\nConcatenated rows with arr3 reshaped:\n", np.concatenate((arr1, arr3_reshaped), axis=0))


Concatenated rows with arr3 reshaped:
 [[ 1  2]
 [ 3  4]
 [ 9 10]]


####Vectorization - allows element-wise operations

In [ ]:
print("arr1:\n", arr1)
print("\narr2:\n", arr2)

arr1:
 [[1 2]
 [3 4]]

arr2:
 [[5 6]
 [7 8]]


In [ ]:
# Add the two arrays element-wise
result_add = arr1 + arr2
print("Element-wise addition:\n", result_add)

Element-wise addition:
 [[ 6  8]
 [10 12]]


In [ ]:
# Multiply the two arrays element-wise
result_mul = arr1 * arr2
print("Element-wise multiplication:\n", result_mul)

Element-wise multiplication:
 [[ 5 12]
 [21 32]]


In [ ]:
# Dot product/ Matrix multiplication of two arrays
dot_product = np.dot(arr1, arr2)
print("Dot product:\n", dot_product)

Dot product:
 [[19 22]
 [43 50]]


In [ ]:
# Vectorized comparison
print(arr)

# Find elements greater than 3
result_comparison = arr > 3
print("Elements greater than 3:", result_comparison)

[1 2 3 4 5 6]
Elements greater than 3: [False False False  True  True  True]


In [ ]:
# Broadcasting
print("arr1:\n", arr1)
scalar = 2

# Multiply each element of arr6 by the scalar 2 using broadcasting
result_broadcasting = arr1 * scalar
print("\nBroadcasting Example:\n", result_broadcasting)

arr1:
 [[1 2]
 [3 4]]

Broadcasting Example:
 [[2 4]
 [6 8]]


In [ ]:
# Calculate the square of each element in arr1
result_square = np.square(arr1)
print("Square of each element:\n", result_square)

Square of each element:
 [[ 1  4]
 [ 9 16]]


####Array functions

In [ ]:
print('arr1:\n', arr1)

arr1:
 [[1 2]
 [3 4]]


In [ ]:
# Calculate the sum of all elements in arr1
sum_of_elements = np.sum(arr1)
print("Sum of elements:", sum_of_elements)

# Calculate the mean of all elements in arr1
mean_of_elements = np.mean(arr1)
print("Mean of elements:", mean_of_elements)

# Calculate the standard deviation of all elements in arr1
std_dev = np.std(arr1)
print("Standard deviation:", std_dev)

# Calculate the maximum value in arr1
max_value = np.max(arr1)
print("Maximum value:", max_value)

# Calculate the minimum value in arr1
min_value = np.min(arr1)
print("Minimum value:", min_value)

# Find the index of the maximum value in arr1
max_index = np.argmax(arr1)
print("Index of the maximum value:", max_index)

# Find the index of the minimum value in arr1
min_index = np.argmin(arr1)
print("Index of the minimum value:", min_index)

# Shuffle arr
arr4 = np.array([1, 2, 3, 4, 5, 6])
np.random.shuffle(arr4)
print("Shuffled array:", arr4)

# Find the sorted indexes from arr
sorted_indexes = np.argsort(arr4)
print("Sorted indexes:", sorted_indexes)
print("Sorted values:", arr4[sorted_indexes])

# Calc sin, cos and tan & inverse
angle_degrees = 45
angle_radians = np.radians(angle_degrees)
sin_val = np.sin(angle_radians)
cos_val = np.cos(angle_radians)
tan_val = np.tan(angle_radians)
arcsin_val = np.degrees(np.arcsin(sin_val))
arccos_val = np.degrees(np.arccos(cos_val))
arctan_val = np.degrees(np.arctan(tan_val))
results = {
      "sin": sin_val,
      "cos": cos_val,
      "tan": tan_val,
      "arcsin": arcsin_val,
      "arccos": arccos_val,
      "arctan": arctan_val
  }
print(results)

Sum of elements: 10
Mean of elements: 2.5
Standard deviation: 1.118033988749895
Maximum value: 4
Minimum value: 1
Index of the maximum value: 1
Index of the minimum value: 2
Shuffled array: [1 2 5 3 6 4]
Sorted indexes: [0 1 3 5 2 4]
Sorted values: [1 2 3 4 5 6]
{'sin': 0.7071067811865475, 'cos': 0.7071067811865476, 'tan': 0.9999999999999999, 'arcsin': 44.99999999999999, 'arccos': 45.0, 'arctan': 45.0}
